/** @file packetType.h
 *
 * 	@author Doowon Kim
 * 	@date Aug. 2014
 */

typedef enum { 	
	ERROR = -1, 
	REQ_FIND_CLOSEST_FINGER = 1,
	RES_FIND_CLOSEST_FINGER_FOUND,
	RES_FIND_CLOSEST_FINGER_NOTFOUND,
	REQ_GET_PRED, RES_GET_PRED,
	REQ_GET_SUCC, RES_GET_SUCC,
	REQ_MODIFY_PRED,
	REQ_GET_KEYS, RES_GET_KEYS,
	REQ_CHECK_ALIVE, RES_CHECK_ALIVE
} PktType;